AWSTemplateFormatVersion: '2010-09-09'
Description: 'S3, CloudFront and (optionally) Route 53'

Parameters:
    ProjectName:
        Type: String
        Default: 'BLOG'
    BucketName:
        Type: String
        Default: 'blog'
    Domain:
        Type: String
        Default: ''
        Description: 'The public domain for the site.'
    AcmCertificateArn:
        Type: String
        Default: ''
        Description: 'The ARN of the ACM certificate in us-east-1 (Required for custom domain)'
    EnableRoute53:
        Type: String
        Default: 'false'
        AllowedValues:
            - 'true'
            - 'false'
        Description: 'Set to true to create Route53 records for the blog subdomain'

Conditions:
    UseRoute53: !Equals [!Ref EnableRoute53, 'true']
    UseCustomCert: !Not [!Equals [!Ref AcmCertificateArn, '']]

Resources:
    WebsiteBucket:
        Type: AWS::S3::Bucket
        Properties:
            BucketName: !Sub '${BucketName}-site-${AWS::AccountId}'
            WebsiteConfiguration:
                IndexDocument: index.html
                ErrorDocument: index.html
            PublicAccessBlockConfiguration:
                BlockPublicAcls: true
                BlockPublicPolicy: true
                IgnorePublicAcls: true
                RestrictPublicBuckets: true

    WebsiteBucketOAC:
        Type: AWS::CloudFront::OriginAccessControl
        Properties:
            OriginAccessControlConfig:
                Name: !Sub '${ProjectName}-OAC'
                Description: Access control for CloudFront to S3
                SigningBehavior: always
                SigningProtocol: sigv4
                OriginAccessControlOriginType: s3

    WebsiteBucketPolicy:
        Type: AWS::S3::BucketPolicy
        Properties:
            Bucket: !Ref WebsiteBucket
            PolicyDocument:
                Version: '2012-10-17'
                Statement:
                    - Sid: AllowCloudFrontServicePrincipal
                      Effect: Allow
                      Principal:
                          Service: cloudfront.amazonaws.com
                      Action: s3:GetObject
                      Resource: !Sub '${WebsiteBucket.Arn}/*'

    WebsiteDistribution:
        Type: AWS::CloudFront::Distribution
        Properties:
            DistributionConfig:
                Enabled: true
                Aliases:
                    - !If [UseCustomCert, !Ref Domain, !Ref 'AWS::NoValue']
                DefaultRootObject: index.html
                Origins:
                    - Id: !Sub '${ProjectName}-S3Origin'
                      DomainName: !GetAtt WebsiteBucket.RegionalDomainName
                      S3OriginConfig: {}
                      OriginAccessControlId: !Ref WebsiteBucketOAC
                DefaultCacheBehavior:
                    TargetOriginId: !Sub '${ProjectName}-S3Origin'
                    ViewerProtocolPolicy: redirect-to-https
                    AllowedMethods:
                        - GET
                        - HEAD
                    CachedMethods:
                        - GET
                        - HEAD
                    Compress: true
                    ForwardedValues:
                        QueryString: false
                        Cookies:
                            Forward: none
                CustomErrorResponses:
                    - ErrorCode: 403
                      ResponsePagePath: /index.html
                      ResponseCode: 200
                      ErrorCachingMinTTL: 0
                    - ErrorCode: 404
                      ResponsePagePath: /index.html
                      ResponseCode: 200
                      ErrorCachingMinTTL: 0
                ViewerCertificate:
                    AcmCertificateArn: !If
                        - UseCustomCert
                        - !Ref AcmCertificateArn
                        - !Ref 'AWS::NoValue'
                    CloudFrontDefaultCertificate: !If
                        - UseCustomCert
                        - !Ref 'AWS::NoValue'
                        - true
                    SslSupportMethod: !If
                        - UseCustomCert
                        - sni-only
                        - !Ref 'AWS::NoValue'
                    MinimumProtocolVersion: !If
                        - UseCustomCert
                        - TLSv1.2_2021
                        - !Ref 'AWS::NoValue'
                PriceClass: PriceClass_100

    Route53HostedZone:
        Type: AWS::Route53::HostedZone
        Condition: UseRoute53
        Properties:
            Name: !Ref Domain

    Route53Record:
        Type: AWS::Route53::RecordSet
        Condition: UseRoute53
        Properties:
            HostedZoneId: !Ref Route53HostedZone
            Name: !Ref Domain
            Type: A
            AliasTarget:
                DNSName: !GetAtt WebsiteDistribution.DomainName
                HostedZoneId: Z2FDTNDATAQYW2

Outputs:
    CloudFrontDistributionId:
        Description: 'The ID of the CloudFront distribution'
        Value: !Ref WebsiteDistribution

    CloudFrontDomainName:
        Description: 'The domain name of the CloudFront distribution'
        Value: !GetAtt WebsiteDistribution.DomainName

    Route53NSRecords:
        Description: 'Name servers for the Route53 hosted zone'
        Condition: UseRoute53
        Value: !Join [',', !GetAtt Route53HostedZone.NameServers]

    Route53HostedZoneID:
        Description: 'ID for the Route 53 hosted zone'
        Condition: UseRoute53
        Value: !Ref Route53HostedZone
